package com.smartbi.controller;

import com.smartbi.dto.QueryRequest;
import com.smartbi.dto.QueryResponse;
import com.smartbi.service.QueryService;
import lombok.extern.slf4j.Slf4j;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping("/api")
@RequiredArgsConstructor
@Slf4j
public class QueryController {

    private final QueryService queryService;

    /**
     * Unified NL2SQL query endpoint.
     * <p>
     * Request contains a natural language question.
     * Response contains:
     * - generated and validated SQL
     * - query data rows
     * - explanation text generated by AI
     */
    @PostMapping("/query")
    public QueryResponse query(@Valid @RequestBody QueryRequest request) {
        log.info("API /api/query called. question={}", request.getQuestion());
        return queryService.handleQuery(request);
    }
}
